spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/${DB_NAME:notesdb}
    username: ${DB_USR_NAME:postgres}
    password: ${DB_USR_PASS:admin}
    driverClassName: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  application:
   name: NotesApplication
  jackson:
   serialization:
    fail-on-empty-beans: false   
    
    
jwt:
  header: Authorization
  secret: mySecret
  expiration: 604800
  route:
    authentication:
      path: auth
      refresh: refresh
      token: check    